baseURL: "https://eveneko.com" # ç»‘å®šçš„åŸŸå
title: "Neko Nest" # ç½‘ç«™æ ‡é¢˜
theme: PaperMod # ä¸»é¢˜åç§°

languageCode: "zh" # en-us
DefaultContentLanguage: "zh"
hasCJKLanguage: true # è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡æ—¥æ–‡éŸ©æ–‡ å¦‚æœæ–‡ç« ä¸­ä½¿ç”¨äº†å¾ˆå¤šä¸­æ–‡å¼•å·çš„è¯å¯ä»¥å¼€å¯

enableInlineShortcodes: true
enableEmoji: true # å…è®¸ä½¿ç”¨ Emoji è¡¨æƒ…ï¼Œå»ºè®® true
enableRobotsTXT: true # å…è®¸çˆ¬è™«æŠ“å–åˆ°æœç´¢å¼•æ“ï¼Œå»ºè®® true
hasCJKLanguage: true # è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡æ—¥æ–‡éŸ©æ–‡ å¦‚æœæ–‡ç« ä¸­ä½¿ç”¨äº†å¾ˆå¤šä¸­æ–‡å¼•å·çš„è¯å¯ä»¥å¼€å¯
enableGitInfo: false 

buildDrafts: false # æ˜¯å¦æ„å»ºè‰ç¨¿
buildFuture: false # æ˜¯å¦æ„å»ºæœªæ¥çš„æ–‡ç« 
buildExpired: false # æ˜¯å¦æ„å»ºè¿‡æœŸçš„æ–‡ç« 

googleAnalytics: "" # è°·æ­Œç»Ÿè®¡

paginate: 15 # é¦–é¡µæ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°
summaryLength: 140 # æ–‡ç« æ¦‚è§ˆçš„è‡ªå­—æ•°ï¼Œé»˜è®¤70

minify: # å‹ç¼©è¾“å‡ºé™æ€æ–‡ä»¶
  disableXML: true
  minifyOutput: true

params: # å…¨å±€é…ç½®
  env: production
  title: "Neko Nest" # ç½‘ç«™æ ‡é¢˜
  description: "Neko Nest" # ç½‘ç«™æè¿°

  author: "Eveneko" # ç½‘ç«™ä½œè€…
  # author: ["Me", "You"] # å¤šä¸ªä½œè€…å†™æ³•

  DateFormat: "1999-02-03" # æ—¥æœŸæ ¼å¼
  defaultTheme: auto # defaultTheme: light or  dark
  disableThemeToggle: true # æ˜¯å¦å¯ç”¨ä¸»é¢˜åˆ‡æ¢æŒ‰é’®
  ShowReadingTime: true # æ˜¯å¦å¯ç”¨é˜…è¯»æ—¶é—´å±•ç¤º
  ShowShareButtons: false # æ˜¯éƒ½å¯ç”¨åˆ†äº«æŒ‰é’®
  ShowPostNavLinks: true # å¸–å­ä¸‹æ–¹çš„å…¶ä»–å¸–å­å»ºè®®
  ShowBreadCrumbs: true # æ˜¯å¦å¯ç”¨é¢åŒ…å±‘å¯¼èˆª
  ShowCodeCopyButtons: true # æ˜¯å¦æ˜¾ç¤ºä»£ç å¤åˆ¶æŒ‰é’®
  ShowWordCount: true # æ˜¯å¦æ˜¾ç¤ºå­—æ•°ç»Ÿè®¡
  ShowRssButtonInSectionTermList: true # æ˜¯å¦åœ¨é¡µé¢æ˜¾ç¤º RSS æŒ‰é’®
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false # æ˜¯å¦ç¦ç”¨é¦–é¡µæ»šåŠ¨åˆ°é¡¶éƒ¨
  comments: false # æ˜¯å¦å¯ç”¨è¯„è®ºç³»ç»Ÿ
  hidemeta: false # æ˜¯å¦éšè— Meta ä¿¡æ¯
  hideSummary: false # æ˜¯å¦éšè—æ–‡ç« æ‘˜è¦
  showtoc: true # æ˜¯å¦æ˜¾ç¤ºç›®å½•
  tocopen: false # æ˜¯å¦é»˜è®¤å±•å¼€æ–‡ç« ç›®å½•

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true

    # ç½‘ç«™ Favicon å›¾æ ‡ç›¸å…³ä¿¡æ¯
    # å¯åœ¨ https://realfavicongenerator.net/ ç”Ÿæˆ
    # å°†å›¾ç‰‡å¤åˆ¶åˆ° /static ç›®å½•ä¸‹
    # ç„¶åä¿®æ”¹ä¸‹é¢ä»£ç ä¸­çš„æ–‡ä»¶å
    favicon: "images/logo.svg"
    favicon16x16: "images/logo.svg"
    favicon32x32: "images/logo.svg"
    apple_touch_icon: "images/logo.svg"
    safari_pinned_tab: "images/logo.svg"

  label:
    text: "Neko Nest" # ä½¿ç”¨æ–‡æœ¬æ›¿ä»£ Logo æ ‡ç­¾
    icon: /images/logo.svg # ç½‘ç«™ Logo å›¾ç‰‡ï¼ˆ/static ä¸‹é¢çš„æ–‡ä»¶åç§°ï¼‰
    iconHeight: 35 # å›¾æ ‡é«˜åº¦

  # ä¸»é¡µå±•ç¤ºæ¨¡å¼
  # ä¸ªäººä¿¡æ¯æ¨¡å¼
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Eveneko"
    subtitle: "é™ªä½ åº¦è¿‡æ¼«é•¿å²æœˆ"
    imageUrl: "/images/avatar.jpeg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: avatar
    buttons:
      - name: ğŸ“„ CV
        url: cv.png

  # ä¸»é¡µ - ä¿¡æ¯æ¨¡å¼ï¼ˆé»˜è®¤ï¼‰
  homeInfoParams:
    Title: "Eveneko"
    Content: "é™ªä½ åº¦è¿‡æ¼«é•¿å²æœˆ"

  #  ä¸»é¡µ - ä¿¡æ¯æ¨¡å¼ å›¾æ ‡å±•ç¤º
  socialIcons:
    - name: github
      url: "https://github.com/Eveneko"
    - name: qq
      url: "images/qq.png"
    - name: wechat
      url: "images/wx.jpg"
    - name: email
      url: "mailto:huyubin0203@gmail.com"
    - name: linkedin
      url: "https://www.linkedin.com/in/yubin-hu-7855861a0/"

  # ç«™é•¿éªŒè¯
  analytics:
    google:
      SiteVerificationTag: ""
    bing:
      SiteVerificationTag: ""
    yandex:
      SiteVerificationTag: ""

  # æ–‡ç« å°é¢è®¾ç½®
  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # å…³è”ç¼–è¾‘
  editPost:
    URL: "https://github.com/DejavuMoe/hugo-start/edit/master/content/posts"
    Text: "Edit on GitHub" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]


# é¡¶éƒ¨å¯¼èˆªæ 
menu:
  main:
    - identifier: "æœç´¢"
      name: "ğŸ” æœç´¢"
      url: /search/
      weight: 10
    - identifier: "æ—¶é—´è½´"
      name: "ğŸ•™ æ—¶é—´è½´"
      url: /archives/
      weight: 20
    - identifier: "åˆ†ç±»"
      name: "ğŸ§© åˆ†ç±»"
      url: /categories/
      weight: 30
    - identifier: "æ ‡ç­¾"
      name: "ğŸ·ï¸ æ ‡ç­¾"
      url: /tags/
      weight: 40
    - identifier: "å‹é“¾"
      name: "ğŸ‘¬ å‹é“¾"
      url: /links/
      weight: 50
    - identifier: "å…³äº"
      name: "ğŸ™‹ğŸ»â€â™‚ï¸ å…³äº"
      url: /about/
      weight: 60

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true

markup:
  goldmark:
    renderer:
      unsafe: true # HUGO é»˜è®¤è½¬ä¹‰ Markdown æ–‡ä»¶ä¸­çš„ HTML ä»£ç ï¼Œå¦‚éœ€å¼€å¯çš„è¯
  highlight:
    # anchorLineNos: true
    codeFences: true # ä»£ç å›´æ åŠŸèƒ½ï¼Œè¿™ä¸ªåŠŸèƒ½ä¸€èˆ¬éƒ½è¦è®¾ä¸º true çš„ï¼Œä¸ç„¶å¾ˆéš¾çœ‹ï¼Œå°±æ˜¯å¹²å·´å·´çš„-ä»£ç æ–‡å­—ï¼Œæ²¡æœ‰é¢œè‰²ã€‚
    guessSyntax: true # çŒœæµ‹è¯­æ³•ï¼Œè¿™ä¸ªåŠŸèƒ½å»ºè®®è®¾ç½®ä¸º true, å¦‚æœä½ æ²¡æœ‰è®¾ç½®è¦æ˜¾ç¤ºçš„è¯­è¨€åˆ™ä¼šè‡ªåŠ¨åŒ¹é…ã€‚
    lineNos: true # æ˜¯å¦æ˜¾ç¤ºè¡Œå·ï¼Œæˆ‘æ¯”è¾ƒå–œæ¬¢æ˜¾ç¤ºï¼Œæ‰€ä»¥æˆ‘è®¾ç½®çš„ä¸º true.
    noClasses: true # ä½¿ç”¨ class æ ‡ç­¾ï¼Œè€Œä¸æ˜¯å†…åµŒçš„å†…è”æ ·å¼
    tabWidth: 4
    style: monokai

privacy:
  vimeo:
    disabled: true
    enableDNT: true
    simple: true

  twitter:
    disabled: true
    enableDNT: true # æ˜¯å¦å¯ç”¨æ·»åŠ â€œè¯·å‹¿è·Ÿè¸ªâ€ HTTP å¤´ã€‚
    simple: true # å¦‚æœå¯ç”¨ç®€å•æ¨¡å¼ï¼Œå°†å»ºç«‹ä¸€ä¸ªé™æ€çš„ã€æ—  JS ç‰ˆæœ¬çš„æ¨æ–‡ã€‚

  instagram:
    disabled: true
    simple: true

  youtube:
    disabled: true
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true # ç¦ç”¨ Hugo æä¾›çš„å†…è”æ ·å¼
  twitter:
    disableInlineCSS: true # ç¦ç”¨ Hugo æä¾›çš„å†…è”æ ·å¼
